# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a the component elements of the first parameter of beta
#' @param b the component elements of the two parameter of beta
#' @param n the parameter of the binomial distribution
#' @return a random sample 
#' @examples
#' \dontrun{
#' rnC<-gibbsC(2,3,100)
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(a, b, n) {
    .Call('_StatComp21027_gibbsC', PACKAGE = 'StatComp21027', a, b, n)
}

